# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bytelink_0_0/design_1_bytelink_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bytelink_0_0 || ORIG_REF_NAME==design_1_bytelink_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bytelink_1_0/design_1_bytelink_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_bytelink_1_0 || ORIG_REF_NAME==design_1_bytelink_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sim_clk_gen_0_0/design_1_sim_clk_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sim_clk_gen_0_0 || ORIG_REF_NAME==design_1_sim_clk_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_1 || ORIG_REF_NAME==design_1_clk_wiz_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sim_rst_gen_0_0/design_1_sim_rst_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sim_rst_gen_0_0 || ORIG_REF_NAME==design_1_sim_rst_gen_0_0} -quiet] -quiet

# XDC: /home1/shivang/github/vivado_ex/QBlink_test/test_qbl/test_qbl.gen/sources_1/bd/design_1/design_1_ooc.xdc
