# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home1/shivang/github/vivado_ex/QBlink_test/test_qbl/test_qbl.srcs/sources_1/bd/design_1/ip/design_1_bytelink_0_0/design_1_bytelink_0_0.xci
# IP: The module: 'design_1_bytelink_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home1/shivang/github/vivado_ex/QBlink_test/test_qbl/test_qbl.gen/sources_1/bd/design_1/ip/design_1_bytelink_0_0/src/SerializationFifo/SerializationFifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SerializationFifo || ORIG_REF_NAME==SerializationFifo} -quiet] -quiet

# XDC: /home1/shivang/github/vivado_ex/QBlink_test/test_qbl/test_qbl.gen/sources_1/bd/design_1/ip/design_1_bytelink_0_0/src/SerializationFifo/SerializationFifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SerializationFifo || ORIG_REF_NAME==SerializationFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home1/shivang/github/vivado_ex/QBlink_test/test_qbl/test_qbl.gen/sources_1/bd/design_1/ip/design_1_bytelink_0_0/src/SerializationFifo/SerializationFifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SerializationFifo || ORIG_REF_NAME==SerializationFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: /home1/shivang/github/vivado_ex/QBlink_test/test_qbl/test_qbl.srcs/sources_1/bd/design_1/ip/design_1_bytelink_0_0/design_1_bytelink_0_0.xci
# IP: The module: 'design_1_bytelink_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home1/shivang/github/vivado_ex/QBlink_test/test_qbl/test_qbl.gen/sources_1/bd/design_1/ip/design_1_bytelink_0_0/src/SerializationFifo/SerializationFifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SerializationFifo || ORIG_REF_NAME==SerializationFifo} -quiet] -quiet

# XDC: /home1/shivang/github/vivado_ex/QBlink_test/test_qbl/test_qbl.gen/sources_1/bd/design_1/ip/design_1_bytelink_0_0/src/SerializationFifo/SerializationFifo.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SerializationFifo || ORIG_REF_NAME==SerializationFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home1/shivang/github/vivado_ex/QBlink_test/test_qbl/test_qbl.gen/sources_1/bd/design_1/ip/design_1_bytelink_0_0/src/SerializationFifo/SerializationFifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SerializationFifo || ORIG_REF_NAME==SerializationFifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
