#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Jun 12 16:05:49 HST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim qbl_tb_behav -key {Behavioral:sim_1:Functional:qbl_tb} -tclbatch qbl_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim qbl_tb_behav -key {Behavioral:sim_1:Functional:qbl_tb} -tclbatch qbl_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

